# Use an official Python runtime as a parent image
FROM python:3.12

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

# Copy the rest of the application's code into the container at /app
COPY . .

# Expose port 10001 to the outside world
EXPOSE 10001

# Command to run the application， 可能需要设置--agent_url，如果main_api中的.env使用的不是docker的同一个网络
CMD ["python", "main_api.py", "--host", "0.0.0.0", "--port", "10001"]
